# Generated by Django 2.1 on 2019-10-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alienvault_url', models.CharField(blank=True, max_length=100)),
                ('kibana_url', models.CharField(blank=True, max_length=100)),
                ('zscaler_url', models.CharField(blank=True, max_length=100)),
                ('sentielone_url', models.CharField(blank=True, max_length=100)),
                ('solarwinds_url', models.CharField(blank=True, max_length=100)),
                ('lead_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
