# Generated by Django 2.1 on 2019-10-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lead_engineer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
