# Generated by Django 2.1 on 2020-01-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0013_auto_20200112_1710'),
        ('users', '0003_client_technical_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='head_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='head_office', to='netscan.sites'),
        ),
    ]
