# Generated by Django 2.1 on 2020-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200112_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
