# Generated by Django 3.0.2 on 2020-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_company_account_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_api',
            field=models.BooleanField(default=False),
        ),
    ]
