# Generated by Django 2.1 on 2020-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
