# Generated by Django 2.1 on 2019-10-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('dns_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alienvault_url', models.CharField(blank=True, max_length=100)),
                ('kibana_url', models.CharField(blank=True, max_length=100)),
                ('zscaler_url', models.CharField(blank=True, max_length=100)),
                ('sentielone_url', models.CharField(blank=True, max_length=100)),
                ('solarwinds_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client_networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Client')),
            ],
            options={
                'verbose_name_plural': 'Client Networks',
            },
        ),
        migrations.CreateModel(
            name='Client_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Client')),
            ],
            options={
                'verbose_name_plural': 'Client Users',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('dns_name', models.CharField(max_length=50)),
                ('scan_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Enginer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Scan_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Device')),
            ],
            options={
                'verbose_name_plural': 'Device Scanned Data',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='lead_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Enginer'),
        ),
        migrations.AddField(
            model_name='agent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.Client'),
        ),
    ]
