# Generated by Django 2.1 on 2019-11-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
        ('netscan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sites',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='device',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Client'),
        ),
        migrations.AddField(
            model_name='client_networks',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client_networks',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='assets_virtualappliance',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_users',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netscan.sites'),
        ),
        migrations.AddField(
            model_name='assets_users',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_tags',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets_tags',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='assets_owners',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='assets_owners',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_networks',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscan.assets_owners'),
        ),
        migrations.AddField(
            model_name='assets_networks',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_networks',
            name='virtual_appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netscan.assets_virtualappliance'),
        ),
        migrations.AddField(
            model_name='assets_master',
            name='asset_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'netscan'), ('model', 'assets_hosts')), models.Q(('app_label', 'netscan'), ('model', 'asset_virtualappliance')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='assets_master',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='assets_master',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netscan.assets_owners'),
        ),
        migrations.AddField(
            model_name='assets_hosts',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netscan.sites'),
        ),
        migrations.AddField(
            model_name='assets_hosts',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_datastores',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
        migrations.AddField(
            model_name='assets_clouds',
            name='tag',
            field=models.ManyToManyField(to='netscan.assets_tags'),
        ),
    ]
