# Generated by Django 2.1 on 2020-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0002_auto_20200109_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_hosts',
            name='ports_open',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
