# Generated by Django 2.1 on 2019-12-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('netscan', '0002_auto_20191202_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_hosts',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Client'),
        ),
    ]
