# Generated by Django 2.1 on 2020-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0003_assets_virtualappliance_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_virtualappliance',
            name='dns_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assets_virtualappliance',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
