# Generated by Django 2.1 on 2019-11-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0003_auto_20191128_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_master',
            name='asset_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'netscan'), ('model', 'assets_hosts')), models.Q(('app_label', 'netscan'), ('model', 'assets_clouds')), models.Q(('app_label', 'netscan'), ('model', 'assets_datastores')), models.Q(('app_label', 'netscan'), ('model', 'assets_users')), models.Q(('app_label', 'netscan'), ('model', 'assets_networks')), models.Q(('app_label', 'netscan'), ('model', 'assets_virtualappliance')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
