# Generated by Django 2.1 on 2019-11-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0004_auto_20191128_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets_master',
            old_name='asset_type',
            new_name='type',
        ),
    ]
