# Generated by Django 2.1 on 2020-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0004_auto_20200312_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_virtualappliance',
            name='dns_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assets_virtualappliance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
