# Generated by Django 2.1 on 2019-12-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0004_auto_20191204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_networks',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netscan.assets_owners'),
        ),
    ]
