# Generated by Django 2.1 on 2020-01-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0005_auto_20200110_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_datastores',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netscan.sites'),
        ),
    ]
