# Generated by Django 2.1 on 2019-11-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0005_auto_20191128_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enginer',
        ),
    ]
