# Generated by Django 2.1 on 2020-03-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('netscan', '0005_auto_20200312_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_virtualappliance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Client'),
        ),
    ]
