# Generated by Django 2.1 on 2020-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0006_assets_datastores_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_datastores',
            name='external_asset',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
