# Generated by Django 2.1 on 2019-11-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0006_delete_enginer'),
    ]

    operations = [
        migrations.CreateModel(
            name='assets_ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'tcp'), (2, 'udp')], default=1)),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Asset Ports',
            },
        ),
    ]
