# Generated by Django 2.1 on 2019-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0007_auto_20191206_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_networks',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client_networks',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='client',
        ),
        migrations.AlterField(
            model_name='assets_users',
            name='manager',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assets_users',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Client_networks',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
