# Generated by Django 2.1 on 2019-11-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0007_assets_ports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets_ports',
            options={'verbose_name_plural': 'Assets Ports'},
        ),
        migrations.RenameField(
            model_name='assets_ports',
            old_name='state',
            new_name='type',
        ),
    ]
