# Generated by Django 2.1 on 2020-01-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0008_auto_20200110_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_clouds',
            name='external_asset',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assets_clouds',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netscan.sites'),
        ),
    ]
