# Generated by Django 2.1 on 2020-01-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0010_assets_networks_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_networks',
            name='virtual_appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netscan.assets_virtualappliance'),
        ),
    ]
