# Generated by Django 2.1 on 2020-01-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0012_auto_20200110_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_tags',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
