# Generated by Django 2.1 on 2020-01-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0013_auto_20200112_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='is_headoffice',
        ),
    ]
