# Generated by Django 3.0.2 on 2020-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0014_remove_sites_is_headoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_hosts',
            name='external_asset',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
