# Generated by Django 3.0.2 on 2020-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0016_auto_20200129_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets_hosts',
            name='ports_open',
        ),
        migrations.AddField(
            model_name='assets_hosts',
            name='ports',
            field=models.ManyToManyField(to='netscan.assets_ports'),
        ),
    ]
