# Generated by Django 3.0.2 on 2020-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0019_auto_20200204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_hosts',
            name='last_boot',
            field=models.DateTimeField(null=True),
        ),
    ]
