# Generated by Django 3.0.2 on 2020-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0020_auto_20200204_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_hosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
